# Generated by Django 3.0.6 on 2020-05-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='times_minutes',
            new_name='time_minutes',
        ),
    ]
